In [1]:
import numpy as np

arr = np.linspace(1,20,20,dtype=int)

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)
1
20
int64


In [6]:
import numpy as np
np.random.seed(1)
a = np.random.randint(0, 50, (4, 5))
print(a)
print(a.itemsize)
print(a.shape)
print(a.dtype)
print(a.ndim)

[[37 43 12  8  9]
 [11  5 15  0 16]
 [ 1 12  7 45  6]
 [25 20 37 18 20]]
8
(4, 5)
int64
2


In [ ]:
np.random.seed(0)
b = np.random.randint(10, size=(3,4))
print(b[:2,:2])
print(b[:,::2])
print(b[:,::-1])

[[5 8]
 [0 0]]
[[5 9]
 [0 1]
 [6 2]]
[[5 9 8 5]
 [7 1 0 0]
 [4 2 9 6]]


In [ ]:
np.random.seed(0)

c= np.random.randint(10, size=(3,4))
print(c)
print(c[:2,:2])
c[1,2] = 99
print(c)

    


In [9]:
d=np.linspace(1,20,20,dtype=int)
print(d)
print(d.shape)
print(d.ndim)
print(d.size)
print(d.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)
1
20
int64


In [12]:
np.random.seed(0)
arr=np.random.randint(50, size=(4,5))
print(arr.itemsize)
print(arr.nbytes)


8
160


In [15]:
arr1=np.arange(1,13).reshape(3,4)
print(arr1[2,3])
print(arr1[-1])
print(arr1[:,3])

12
[ 9 10 11 12]
[ 4  8 12]


In [3]:
import numpy as np

d= np.arange(25).reshape(5,5)
print(d)

e= d[:3,:4]
e[0,0] = 99
print(d)
print(e)
f= d[:3,:4].copy()
f[0,0] = 93
print(d)
print(f)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[99  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[99  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]
[[99  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[93  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]


In [4]:
x=np.arange(12)
print(x)
y=x.reshape(3,4)
print(y)
z=x.reshape((12,1))
i=x[:,np.newaxis]

print(z)
print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [6]:
np.random.seed(0)
a = np.random.randint(0,10, size =(2,3))
b = np.random.randint(0,10, size =(2,3))
print(a)
print(b)

w=np.vstack((a,b))
m=np.concatenate((a,b), axis=0)

print(w)
print(m)

o= np.hstack((a,b))
n= np.concatenate((a,b), axis=1)
print(o)
print(n)


[[5 0 3]
 [3 7 9]]
[[3 5 2]
 [4 7 6]]
[[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]]
[[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]]
[[5 0 3 3 5 2]
 [3 7 9 4 7 6]]
[[5 0 3 3 5 2]
 [3 7 9 4 7 6]]


In [7]:
v=np.arange(15)
print(v)

d,f,g=np.split(v,[5,10])
print(d)
print(f)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [8]:
h=np.arange(24).reshape(6,4)

print(h)
j,k=np.hsplit(h,[2])
print(j)
print(k)

l,u=np.vsplit(h,[2])
print(l)
print(u)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
