In [2]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(arr)
print(type(arr))




[10 20 30 40 50]
<class 'numpy.ndarray'>


In [3]:
ar = np.array([[1,2],[4,5],[7,8]])

print(ar)


[[1 2]
 [4 5]
 [7 8]]


In [4]:
x= np.array([2,3,4],dtype=float)
print(x,type(x))

[2. 3. 4.] <class 'numpy.ndarray'>


In [6]:
y=np.zeros(6)

print(y)

[0. 0. 0. 0. 0. 0.]


In [8]:
z= np.ones((3,4),dtype=int)

print(z,type(z))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] <class 'numpy.ndarray'>


In [ ]:
#5
e= np.empty((2,2))
print(e)

#the value of e is random because it contains garbage values.

[[4.65003377e-310 0.00000000e+000]
 [4.65059597e-310 4.65059597e-310]]


In [ ]:
q= np.arange(0,20,2)
print(q)

#in this, the start paprmemter is inclusive but end parameter is exclusive.

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
s= np.linspace(0,1,6)

print(s)

#in this, the start and end parameters are inclusive.

[0.  0.2 0.4 0.6 0.8 1. ]


In [13]:
a=np.random.random((3,3))
print(a)

[[0.30911255 0.45647683 0.13267738]
 [0.60944407 0.65857012 0.34731536]
 [0.68226947 0.97898459 0.93614827]]
