In [3]:
import numpy as np 

np.random.seed(1)


a = np.random.randint(10, size=(10))
print(a)



print(np.sort([a]))

#2nd

i = np.argsort(a)
print(i)
print(a.sort())



[5 8 9 5 0 0 1 7 6 9]
[[0 0 1 5 5 6 7 8 9 9]]
[5 4 6 0 3 8 7 1 2 9]
None


In [5]:
np.random.seed(1)

b=np.random.randint(24, size=(4,6))

print(b)

c = np.sort(b, axis=0)
print(c)
d = np.sort(b, axis=1)
print(d)

[[ 5 11 12  8  9 11]
 [ 5 15  0 16  1 12]
 [ 7 13  6 18 20  5]
 [18 20 11 10 14 18]]
[[ 5 11  0  8  1  5]
 [ 5 13  6 10  9 11]
 [ 7 15 11 16 14 12]
 [18 20 12 18 20 18]]
[[ 5  8  9 11 11 12]
 [ 0  1  5 12 15 16]
 [ 5  6  7 13 18 20]
 [10 11 14 18 18 20]]


In [14]:
np.random.seed(1)

e = np.random.randint(15, size=(15))
print(e)
print(np.partition(e,4))

np.sort(e)

[ 5 11 12  8  9 11  5  0  0  1 12  7 13 12  6]
[ 0  0  1  5  5  6  7  8  9 11 11 12 12 12 13]


array([ 0,  0,  1,  5,  5,  6,  7,  8,  9, 11, 11, 12, 12, 12, 13])

In [24]:
import numpy as np

student_names = np.array(["Aisha", "Ben", "Carlos", "Divya", "Ethan"])
scores = np.array([78, 92, 65, 88, 71])

rank = np.argsort(scores)
print(student_names[rank], scores[rank])

['Carlos' 'Ethan' 'Aisha' 'Divya' 'Ben'] [65 71 78 88 92]


In [ ]:

X = np.random.rand(10, 2)
dist_sq = np.sum((X[:, np.newaxis, :] - X[np.newaxis, :, :]) ** 2, axis=-1)
nearest_neighbors = np.argsort(dist_sq, axis=1)[:, 1:3]
print(nearest_neighbors)


[[3 5]
 [6 9]
 [0 5]
 [0 5]
 [9 7]
 [0 6]
 [5 0]
 [4 9]
 [2 7]
 [4 7]]
