In [3]:
import numpy as np

name=['Alice','Bob','Charlie','David','Eva']
age=[25,30,35,40,45]
weight=[55.8,70.7,80.5,90.0,60.2]

data=np.zeros(
    5,
    dtype=({
        'names':('name','age','weight'),
        'formats':('U10','i4','f8')
    })
)
print("Structured array using a compound data type")
print(data.dtype)

data['name']=name
data['age']=age
data['weight']=weight

print("filled structured array")
print(data)

print("all names")
print(data['name'])

print("first row of data")
print(data[0])

print("names from the last row")
print(data[-1]['name'])

print("names where age is under 30")
print(data[data['age'] < 30]['name'])

#dictonary method
np.dtype({
    'names':('name','age','weight'),
    'formats':('U10','i4','f8')
})

np.dtype({
    'names':('name','age','weight'),
    'formats':((np.str_,10),int,np.float32)
})
np.dtype([
    ('name','S10'),
    ('age','i4'),
    ('weight','f8')
])

np.dtype('S10,i4,f8')

Structured array using a compound data type
[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
filled structured array
[('Alice', 25, 55.8) ('Bob', 30, 70.7) ('Charlie', 35, 80.5)
 ('David', 40, 90. ) ('Eva', 45, 60.2)]
all names
['Alice' 'Bob' 'Charlie' 'David' 'Eva']
first row of data
('Alice', 25, 55.8)
names from the last row
Eva
names where age is under 30
['Alice']


dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [7]:
tp = np.dtype([
    ('id', 'i8'),
    ('mat', 'f8', (3, 3))
])

x= np.zeros(1, dtype=tp)

print(x[0])


(0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])


In [5]:
print(x['mat'][0])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np


data_rec = data.view(np.recarray)
print(data_rec.age)

%timeit 